// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCON7NvbSb7ciz6S9VEcB7oBLlthTQE83I',
    appId: '1:843103345943:web:de1bfddf89ddef08046b52',
    messagingSenderId: '843103345943',
    projectId: 'demoflutterlogin-52b05',
    authDomain: 'demoflutterlogin-52b05.firebaseapp.com',
    storageBucket: 'demoflutterlogin-52b05.firebasestorage.app',
    measurementId: 'G-PXW8XH9ZTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcWT8tTRAaxDzxfOKeDgwOLZad5F-G3Zo',
    appId: '1:843103345943:android:501b6555f458b5b9046b52',
    messagingSenderId: '843103345943',
    projectId: 'demoflutterlogin-52b05',
    storageBucket: 'demoflutterlogin-52b05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuX19erEUzEBKk9wHTSRDL49tXb0fRzU4',
    appId: '1:843103345943:ios:837c8916cf2a9f1c046b52',
    messagingSenderId: '843103345943',
    projectId: 'demoflutterlogin-52b05',
    storageBucket: 'demoflutterlogin-52b05.firebasestorage.app',
    iosClientId:
        '843103345943-qv4883cqnnr3aasaa7manv2d6jjf9ghp.apps.googleusercontent.com',
    iosBundleId: 'com.CuongVC.fluttertodosappsupabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuX19erEUzEBKk9wHTSRDL49tXb0fRzU4',
    appId: '1:843103345943:ios:837c8916cf2a9f1c046b52',
    messagingSenderId: '843103345943',
    projectId: 'demoflutterlogin-52b05',
    storageBucket: 'demoflutterlogin-52b05.firebasestorage.app',
    iosClientId:
        '843103345943-qv4883cqnnr3aasaa7manv2d6jjf9ghp.apps.googleusercontent.com',
    iosBundleId: 'com.CuongVC.fluttertodosappsupabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCON7NvbSb7ciz6S9VEcB7oBLlthTQE83I',
    appId: '1:843103345943:web:76e86132b06e37ea046b52',
    messagingSenderId: '843103345943',
    projectId: 'demoflutterlogin-52b05',
    authDomain: 'demoflutterlogin-52b05.firebaseapp.com',
    storageBucket: 'demoflutterlogin-52b05.firebasestorage.app',
    measurementId: 'G-GF4MB03CQL',
  );
}
